In [1]:
import torch
from torch import nn 

import utils

### Parameters Management

In [2]:
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))

Access

In [3]:
net.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.1654,  0.3714, -0.3347, -0.4746],
                      [-0.1869, -0.1555,  0.3110, -0.3768],
                      [ 0.4713,  0.0800, -0.4692,  0.3212],
                      [-0.1601, -0.4167,  0.4114,  0.1254],
                      [-0.2518, -0.0732,  0.2053,  0.3222],
                      [ 0.2893,  0.3394, -0.0371, -0.2011],
                      [-0.3940,  0.4577, -0.4176,  0.1692],
                      [ 0.1137,  0.2418, -0.3441, -0.1119]])),
             ('0.bias',
              tensor([ 0.2088, -0.3896,  0.1596, -0.1241, -0.1361,  0.1408,  0.1640,  0.3152])),
             ('2.weight',
              tensor([[-0.2573,  0.0414,  0.0143, -0.1230, -0.1688,  0.1757, -0.1222, -0.1126]])),
             ('2.bias', tensor([0.1169]))])

In [4]:
net[0].state_dict()

OrderedDict([('weight',
              tensor([[ 0.1654,  0.3714, -0.3347, -0.4746],
                      [-0.1869, -0.1555,  0.3110, -0.3768],
                      [ 0.4713,  0.0800, -0.4692,  0.3212],
                      [-0.1601, -0.4167,  0.4114,  0.1254],
                      [-0.2518, -0.0732,  0.2053,  0.3222],
                      [ 0.2893,  0.3394, -0.0371, -0.2011],
                      [-0.3940,  0.4577, -0.4176,  0.1692],
                      [ 0.1137,  0.2418, -0.3441, -0.1119]])),
             ('bias',
              tensor([ 0.2088, -0.3896,  0.1596, -0.1241, -0.1361,  0.1408,  0.1640,  0.3152]))])

In [5]:
print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([0.1169], requires_grad=True)
tensor([0.1169])


In [6]:
print(*[(name, param.shape) for name, param in net[0].named_parameters()])
print(*[(name, param.shape) for name, param in net.named_parameters()])

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


Initialization

In [7]:
def init_normal(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, mean = 0, std = 0.01)
        nn.init.zeros_(m.bias)
        
net.apply(init_normal)
net[0].state_dict()

OrderedDict([('weight',
              tensor([[ 2.2847e-03, -4.7551e-03,  6.5838e-04, -2.7397e-03],
                      [-1.6923e-03,  5.9899e-03,  2.4863e-02, -3.0952e-03],
                      [ 2.3483e-02, -1.4370e-03, -6.9487e-03, -1.9369e-02],
                      [-9.4447e-03,  2.5753e-02, -1.2312e-02,  2.6325e-02],
                      [-3.8687e-03, -3.0835e-03,  5.5181e-03,  9.4772e-03],
                      [ 6.6182e-03,  4.5910e-05,  9.4138e-03,  2.0515e-03],
                      [-1.3127e-02, -3.7509e-04,  9.1234e-03,  1.0550e-02],
                      [-1.1195e-02,  4.1804e-03,  1.3402e-02, -1.5924e-03]])),
             ('bias', tensor([0., 0., 0., 0., 0., 0., 0., 0.]))])

In [8]:
def xavier(m):
    if type(m) == nn.Linear:
        nn.init.xavier_uniform_(m.weight)
def init_42(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight, 42)

net[0].apply(xavier)
net[2].apply(init_42)
print(net[0].weight.data[0])
print(net[2].weight.data)

tensor([-0.3107,  0.2346, -0.1663,  0.3566])
tensor([[42., 42., 42., 42., 42., 42., 42., 42.]])


In [9]:
def my_init(m):
    if type(m) == nn.Linear:
        print('Init', *[(name, param.shape) for name,param in m.named_parameters()][0])
        nn.init.uniform_(m.weight, -10, 10)
        m.weight.data *= m.weight.data.abs() >= 5
        
net.apply(my_init)
net[0].weight[:2]

Init weight torch.Size([8, 4])
Init weight torch.Size([1, 8])


tensor([[-0.0000,  0.0000, -0.0000,  5.5290],
        [-6.2070, -7.9787,  6.2097,  6.1233]], grad_fn=<SliceBackward0>)